CONFIG_ZMK_KEYBOARD_NAME="Pavlos' Corne"

# uncomment these two line to add support for encoders to your firmware
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# uncomment the following line to enable the Kyria OLED Display
# CONFIG_ZMK_DISPLAY=y

# uncomment the following lines to enable RGB underglow
# this is off for now because https://github.com/zmkfirmware/zmk/issues/65 is not done. i want lights on layer.
# CONFIG_ZMK_RGB_UNDERGLOW=y

# this is so that the lag on the right side is minimized.
# https://zmk.dev/docs/troubleshooting#connectivity-issues
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
